### ISSUE TITLE
how to implement an object always right in front of the camera in 360 VR.

### ISSUE THREAD

**Issue by flankechen** [MasDennis/Rajawali#1348]
Hi, I am developing with RajawaliVR and trying to place an object always in front of the camera, much like a billboard. When I put my head set on, and it always indicating where I am looking at. a cross for shooting!

for instance, my camera initialed facing negative z axis and positive y axis as up. Setting a position vector like (0,0,-3,1), (-3 just for making it "not so close" to the camera). For every frame, I multiple this position vector with the head vew matrix, by which the VR renderer set up the camera orientation, to get the new position vector. Then just set the object to this new position.

float[] posVec4 = {0, 0, -3, 1.0f};
Matrix.multiplyMV(newPosition4, 0, mHeadViewMatrix, 0, posVec4, 0);
mRoam.setPosition(-newPosition4[0], -newPosition4[1], newPosition4[2]);

Perfect facing negative z direction! But when I yaw 90 and looking up and down. the object stop following my head move! 
I get that mHeadViewMatrix is always for negative z, in which Yaw, pitch and roll works perfect . But as I turn and heading positive X and look up and down, I am pitching my head but still rolling for negative z direction!

Any idea, suggestion?

Thanks in advance.

**Comment by dcerisano** [comment]
Given that you  are using the excellent RajawaliVR class, your camera orientation quaternion is already being set directly from its HeadTransform rotational matrix. (See rajawalivr.RajawaliVRRenderer)

Since this bit of nasty is out of the way, you are already in the wonderful world of quaternions.

So given:
a RajawaliVRRenderer, renderer 
an Object3D, crosshair and;
a quaternion, q

Placing the following calculus in renderer.onDrawFrame() will project a crosshair directly in front of the viewer in perfect orthogonal orientation (the camera inverse):

``renderer.getCurrentScene().getCamera().getOrientation(q);
crosshair.setOrientation(pointerq.inverse());
``
You may need to 
crosshair.setDoubleSided(true) or 
crosshair.setRotY(90) to see it.

An even easier way would be to simply add a small ScreenQuad onto your scene and draw the crosshair on it. This is a way to do a full HUD.

Also keep in mind some advice from Oculus about HUD graphics: "If it ain't in space, don't put it on your face". HUD graphics can interfere with the VR effects.

**Comment by flankechen** [comment]
@dcerisano Thanks a lot. 
I get your idea and turns out that my question comes from missing the inverse part of the headViewMatrix. 
headViewMatrix transform the object to new position according to head movement. Multiple its inverse would cancel out this transform and keeps the object right in the place.

my code 

Vector3 Position = new Vector3();
float[] newPosition4 = new float[4];
Position = mCenterObj.getPosition();
float[] posVec4 = {(float)Position.x, (float)Position.y, (float)Position.z, 1.0f};

float[] HeadViewMatrix_inv =  new float[16];
Matrix4 HeadViewMatrix4 = new Matrix4();
HeadViewMatrix4.setAll(mHeadViewMatrix);
HeadViewMatrix4 = HeadViewMatrix4.inverse();
HeadViewMatrix4.toFloatArray(HeadViewMatrix_inv);

Matrix.multiplyMV(newPosition4, 0, HeadViewMatrix_inv, 0, posVec4, 0);

MyObject.setPosition(newPosition4[0], newPosition4[1], newPosition4[2]);


Thanks again!

**Comment by dcerisano** [comment]
Glad to help. Note that Rajawali (and Unity too) rely heavily on Quaternion calculus rather than exposing rotational matrix algebra. 

Your solution positions the object properly, but does not change it's orientation (ie does not billboard - just a note to anyone reading this).

Don't forget to to close your issues when resolved.

**Comment by ThunderStick** [comment]
Complete Solution to center any object with a simple call

`public void centerObject(Object3D obj){
        float[] newPosition4 = new float[4];
        float[] posVec4 = {0, 0, -3, 1.0f};
        float[] HeadViewMatrix_inv = new float[16];
        Matrix4 HeadViewMatrix4 = new Matrix4();
        HeadViewMatrix4.setAll(mHeadViewMatrix);
        HeadViewMatrix4 = HeadViewMatrix4.inverse();
        HeadViewMatrix4.toFloatArray(HeadViewMatrix_inv);
        Matrix.multiplyMV(newPosition4, 0, HeadViewMatrix_inv, 0, posVec4, 0);
        obj.setPosition(newPosition4[0], newPosition4[1], newPosition4[2]);

        obj.setLookAt(getCurrentCamera().getPosition());
    }`
