### ISSUE TITLE
OrthographicCamera is not guarded by lock

### ISSUE THREAD

**Issue by kiranpradeep** [MasDennis/Rajawali#1360]
`mProjMatrix` member in `Camera` class is guarded by lock. But in derived `OrthographicCamera` class, member functions `setProjectionMatrix` and `setZoom` which updates the same `mProjMatrix` are not guarded by `mFrustumLock`. Is this intentional ? If not, should I submit pull request ?

**Comment by jwoolston** [comment]
@kiranpradeep This is not intentional. Please submit a pull request and tag this issue in it.

**Comment by jwoolston** [comment]
Fixed via #1362.

**Comment by kiranpradeep** [comment]
@jwoolston 
a dumb question -
Why is `Camera` alone thread guarded when other classes like `BaseObject3D` or `Material` are not ? Couldn't the `Camera` classes access be limited to GL Thread ( mentioned as comment in `RajawaliScene` member `mCamera` ) and the guard be removed ?

**Comment by jwoolston** [comment]
An ongoing project with the library has to increase its ability to have tasks offloaded to other threads. Originally, nothing in the library was thread safe - it all relied on thread confinement. The documentation of the camera not being thread safe is actually the error here, since it was intentionally made thread safe. As for why other classes like the geometry are not, that is a more complex situation. The short answer there is we havn't precisely decided what to do there. The current theory right now is that once added to the scene, other threads wont need to mess with those objects. I realise this is somewhat narrow sighted, but in the use case of live wallpapers, its not that unreasonable. In the end though, a solution to the discrepancy needs to happen, be it confining the camera classes again or making everything else safe.

**Comment by kiranpradeep** [comment]
Thanks @jwoolston
