### ISSUE TITLE
Disabling Bitmap scaling

### ISSUE THREAD

**Issue by kiranpradeep** [MasDennis/Rajawali#1369]
In master branch(`ASingleTexture::setResourceId`) and v0.9 tag, Bitmap scaling is not disabled with
>BitmapFactory.Options opts = new BitmapFactory.Options();
>opts.inScaled = false;

When users provide appropriate images for various densities, shouldn't it be disabled ? Shall I go with a pull request ?

**Comment by jwoolston** [comment]
I am fairly certain this is intentional. The reason being that it was undesirable to have Android's DPI system interfering with texture resolutions, especially since they are assumed constant in many cases. All textures should be placed in the `drawable-nodpi` folder in this case. I will check with @MasDennis as he is the one who wrote that bit, but I am fairly certain it is as expected. In the meantime, you can submit a pull request or not, but I won't be merging it until I hear from him on the matter.

**Comment by MasDennis** [comment]
Thanks @kiranpradeep

This is actually a good addition. Rajawali should use textures depending on dpi instead of using no-dpi. This `inScaled` addition prevents the bitmaps to be scaled to npot textures. If the user has a separate pot texture for each density then all is good :)

I was meant to make this change at some point but never got round to doing it.

**Comment by jwoolston** [comment]
Fixed via #1372.
